apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # These labels are related to deployment
  labels:
    component: backend
    tier: app
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      tier: app
      project: expense
  # Pod definition file starts from here
  template:
    metadata:
      labels:
        component: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1.0

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    tier: app
    project: expense
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port