# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: backend
#   namespace: expense
# data:
#   DB_HOST: mysql # mysql component service name
---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: backend
#   namespace: expense
#   # these labels are deployment related labels
#   labels:
#     component: backend
#     project: expense
#     tier: app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       component: backend
#       project: expense
#       tier: app
#   # pod definition
#   template:
#     metadata:
#       labels:
#         component: backend
#         project: expense
#         tier: app
#     spec:
#       initContainers:
#       - name: init-myservice
#         image: busybox:1.28
#         command: ['sh', '-c', "until nslookup mysql; do echo waiting for myservice; sleep 2; done"]
#       containers:
#       - name: backend
#         image: joindevops/backend:v1.0
#         resources:
#           requests:
#             cpu: "100m"
#             memory: "128Mi"
#           limits:
#             cpu: "150m"
#             memory: "256Mi"
#         # This is related to http 
#         livenessProbe:
#           httpGet:
#             path: /health
#             port: 8080
#           failureThreshold: 2
#           periodSeconds: 5
#           initialDelaySeconds: 30
#         readinessProbe:
#           httpGet:
#             path: /health
#             port: 8080
#           failureThreshold: 2
#           periodSeconds: 5
#           initialDelaySeconds: 30
#         envFrom:
#         - configMapRef:
#             name: backend


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
#   namespace: expense
# spec:
#   selector:
#     component: backend
#     project: expense
#     tier: app
#   ports:
#   - protocol: TCP
#     port: 8080 #service-port
#     targetPort: 8080 #target-port
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    component: mysql
    project: expense
    tier: db
    createdby: pavan
spec: 
  replicas: 2
  # selectors are very important in the deployment
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
      createdby: pavan
  # pod definition 
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
        name: mysql
        image: admin8055/mysql:v1.0
