apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # These labels are related to deployment
  labels:
    component: mysql
    tier: db
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      tier: db
      project: expense
  # Pod definition file starts from here
  template:
    metadata:
      labels:
        component: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0